### ISSUE TITLE
To do list 1- Regarding the User Queries

### ISSUE THREAD

**Issue by smhoban** [christianparobek/skeleSim#1]
To do:

to write questions to let the user modify parameters (e.g. ask them if they want to multiply mutation by 10)
to allow them to skip the questions entirely (choose fastsimcoal or rmetasim)
to allow them to save their megalist and upload an already-created megalist

**Comment by liblig** [comment]
To do:
- to write questions to let the user modify parameters (e.g. ask them if they want to multiply mutation by 10)
- to allow them to skip the questions entirely (choose fastsimcoal or rmetasim)
- to allow them to save their megalist and upload an already-created megalist
- to write documentation: description, vignette, tutorial (appropriate for Team 1's format - use their Rmarkdown template
- to finalize analytical functions/summary stats: tweak according to package updates; include Ne functions from 'HENe'
- to provide example cases and datasets to showcase: power analysis, null models, parameter inference. Try include example SNP, msat, single sequence and multisequence data sets. Try include management/conservation applications, theoretical application (i.e. performance testing of statistics), ... etc.
- to incorporate multiDNA data form for multiple sequences using apex package (will require simulation output in same format, and data form conversion for analyses probably)
- to keep in touch!
