### ISSUE TITLE
test.params@timing slot missing

### ISSUE THREAD

**Issue by christianparobek** [christianparobek/skeleSim#12]
In both `testRunMetaSim.R` and `test.RunSim.R` the code declared a new `skeleSim.params` S4 object then attempts to fill the `@timing` slot. This throws an error saying such a slot doesn't exist - going back to the `skeleSim.classes.R`, I can see where the slots for `skeleSim.params` are defined, and there's not a timing slot there. Should I add it - or am I look at this wrong?

**Comment by EricArcher** [comment]
Good catch! I've added the `@timing` slot to the skeleSim class definition and use it in the first (timing) call to `runSim`.
