### ISSUE TITLE
DESCRIPTION file

### ISSUE THREAD

**Issue by stranda** [christianparobek/skeleSim#16]
Can we edit the DESCRIPTION file directly?  I know that it is created using devtools create_package(), but it remains untouched by roxygen2?

**Comment by EricArcher** [comment]
Yeah, it can be edited by hand once created. I made enough edits to get it to pass R CMD CHECK, but as you can see, it still needs more.
Big one: Who do we want to nominate as the "maintainer"?

**Comment by stranda** [comment]
Ok, thanks.  I changed a couple of imports to depends.  I know that is deprecated, but I was having trouble with the shiny app running unless these packages were loaded first.  depends ensures that that happens whereas imports does not.  At least I think so.

Maintainer....hmmm

**Comment by EricArcher** [comment]
Makes sense. I think CRAN now prefers using ImportFrom in the documentation to import just the necessary functions unless it is desired to have the full functionality of another package available when yours is loaded. Nonetheless, we can leave it as Depends for now and see if it can be cleaned up later.

The skeleSimGUI() function doesn't seem to be available to me. Is there a way you can Export it?

**Comment by EricArcher** [comment]
Belay that last. I hadn't rebuilt and installed. I'll give that a quick shot before I run off...

**Comment by stranda** [comment]
ok, Just in case I rebuilt the NAMESPACE and pushed it all back to github

**Comment by MichelleDBG** [comment]
Is there something more I should be doing to make skeleSimGUI() work or exist? I can't find it.

**Comment by stranda** [comment]
I'd try this approach (you may have already done several of these steps, however)
1) install devtools (install.packages("devtools"))
2) install shiny
3) install shinyFiles
((3.1)) Sean needed this additional step: 
library(devtools)
dev_mode(on=T)
4) install shiny-incubator (using github so: install_github("Rstudio/shiny-incubator")
5) install newest strataG (also using github: install_github("ericarcher/strataG/strataG")
6) install rmetasim 
7) install skeleSim (install_github("christianparobek/skeleSim/skeleSim"))
8) library(skeleSim)
9) then you should be able to run skeleSimGUI()

installing strataG from github might be tricky on windows, I haven't tried it yet

**Comment by MichelleDBG** [comment]
Running. Putting in random numbers and it's in some loop of errors with "migrationNumber" not found

**Comment by smhoban** [comment]
I was unsuccessful in getting strataG from github on my windows box.  I'll try on Ubuntu next.  Michelle is yours on Windows?

**Comment by MichelleDBG** [comment]
I can only get strataG from cran, not github. And I can open the shiny but it is buggy.

I might be home for a snow day today... Kids are off school but I don't know if my work is closed yet. I'll try to make the call later either way.

**Comment by stranda** [comment]
try to install skeleSim now from github.

**Comment by smhoban** [comment]
What version of R is everyone using?  I have 3.0.2 on both my machines but it either doesn't like devtools or doesn't like strataG?

**Comment by christianparobek** [comment]
I believe I have 3.3.2. I was also having some trouble getting dev version of `strataG` to install because of the dependencies - `apex` and `copula`. Looks like these in turn depend on `gsl`, which I had to download on my computer (`sudo apt-get install libgsl0-dev` on Ubuntu) and `phangorn`, the latest version of which seems to depend on `Biostrings`, which is not on CRAN but on Bioconductor ([installation instructions here](https://www.bioconductor.org/packages/2.12/bioc/html/Biostrings.html)). Does this help at all?

Once the `strataG` dependencies are installed, you should be able to:

```
devtools::install_github('ericarcher/strataG/strataG')
library(strataG)

devtools::install_github('christianparobek/skeleSim/skeleSim')
library(skeleSim)
```

**Comment by stranda** [comment]
I'm running r-devel .  I had the same dependency problem installing strataG; solved it the way that Christian outlines

**Comment by MichelleDBG** [comment]
I can't seem to get that Bioconductor biostrings to load because 'ncdf4' has non-zero exit status. I've tried to load RNetCDF. Not working. 

I'm running 3.2.3.  

I wonder if my failure to load Bioconductor is causing a looping error now: "Found more than one class "connection" in cache; using the first, from namespace 'BiocGenerics' ". It's trying to build a forward time simulation.

**Comment by christianparobek** [comment]
I know nothing about this, but looks like `ncdf4` is a package on CRAN. Have you tried installing that then installing `Biostrings`?

I get that same "Found more than once class..." comment when I run the Shiny code as well, even though I was able to load `Biostrings`.

**Comment by smhoban** [comment]
Christian how did you get phanghorn installed?

**Comment by christianparobek** [comment]
I think `phangorn` required the `Biostrings`? So I tried just installing `phangorn` in RStudio and it failed, so I installed `Biostrings` as described above. Did this work for you?

**Comment by MichelleDBG** [comment]
Biostrings gave me trouble but mostly my issues seem to have come from ending up with two library folders and R kept getting confused as to which folder I wanted it to install into or attach from. I'm not sure the best way to solve that problem... 

Running the shiny:  
I get: 
Warning: Unhandled error in observer: object 'rms.run' not found
observeEvent(rValues$ssClass)
ERROR: [on_request_read] connection reset by peer  
 when I unselected the simulator (coalescent) to see what happened. it shut down the shiny page and all seems stuck...

**Comment by stranda** [comment]
Given that these issues have been resolved, I think, I'm closing
