### ISSUE TITLE
missing data during analyses

### ISSUE THREAD

**Issue by stranda** [christianparobek/skeleSim#17]
Though we dismissed the idea of missing data in the analytical functions a month or so ago, I think we may need to resurrect it.  During simulations there should be no problems with missing loci or individual genotypes.  However, it is possible and even likely that in forward time simulations some populations and even entire population systems can go extinct.  This might happen when simulating source-sink dynamics or varying extinction rates among populations.

I have altered the function 'landscape.make.genind' to actually work (it wasn't earlier today?!?) and it creates a genind object.  This object has a slot called 'pop' that contains the population identities of each individual in the genind object.

So we can test for extinction by taking the total number of populations simulated (stored in ssClass@scenarios[[x]]@numpops) and checking that there are individuals present from each of the population numbers from 1 -> the total. 

As I said on the hangout today, I'm a little fuzzy on how this can be accommodated by the analytical routines...

**Comment by smhoban** [comment]
After testing for extinction, if extinction has occurred, we will could...
-insert, in the appropriate place, an empty population in genind object, with a name (if the analysis function can handle an empty pop'n)
-keep population names passed through each step, from metasim to gen ind, to keep track of

As Allan says, we need to see what will happen with the analyses programs if a population is empty.  

I think when passing results of the analyses we are taking entire lines or matrices, which will be a challenge to insert NAs in the right place

**Comment by MichelleDBG** [comment]
Where will the population names be held in the params object (so I can fill in NAs for extinct populations in the analyses function)? 

The number of populations slot won't change even if populations go extinct? If I set a variable to strataNames of the current params@rep.sample will it drop populations that have gone to zero?

**Comment by EricArcher** [comment]
This could be an issue that we'll have to play with. The number of populations slot in the skeleSim object won't change, but the number of populations output by a simulator could vary. We don't currently have a holder for population names, so you can choose to call them whatever you want (e.g. Pop1, Pop2, etc.). I can see an issue if you have Pop1, Pop2, and Pop3, and Pop2 goes extinct in a replicate. I'll have to check to see how that gets named in the output for fastsimcoal. Will do in the next week and get back to you.
