### ISSUE TITLE
strataG new version required to build skeleSim

### ISSUE THREAD

**Issue by stranda** [christianparobek/skeleSim#18]
I found that I had to clone strataG from Eric's github repository and build locally to make sure that skeleSim would build.  The current CRAN version does not export something...

**Comment by christianparobek** [comment]
Here's the link:
https://github.com/EricArcher/strataG

This dev version will require installation of some dependencies. One of the dependencies, `apex`, depends on `phangorn`, which depends on `Biostrings` which [is on Bioconductor](https://www.bioconductor.org/packages/2.12/bioc/html/Biostrings.html) - not CRAN.

**Comment by MichelleDBG** [comment]
I am trying to run a simulation to produce a skeleSim object to test in the analysis_funcs. I get Fastsimcoal and set some parameters. It is now giving me the looping error: 
"Found more than one class "connection" in cache; using the first, from namespace 'BiocGenerics' "

I installed phangorn, apex, and Biostrings following the Bioconductor instructions. Any ideas what I've got wrong with BioGenerics?

**Comment by christianparobek** [comment]
I get that same message as well...

**Comment by smhoban** [comment]
Did this get resolved?

**Comment by smhoban** [comment]
On windows I still get an error with 'dplyr'.  Just FYI.  I'll try on ubuntu

*\* preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'dplyr'
Error : package 'apex' could not be loaded
ERROR: lazy loading failed for package 'strataG'
- removing 'C:/Users/seanmh/Documents/R/win-library/3.2/strataG'
- restoring previous 'C:/Users/seanmh/Documents/R/win-library/3.2/strataG'
  Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Users\seanmh\Documents\R\win-library\3.2\00LOCK-strataG\strataG\libs\i386\strataG.dll to C:\Users\seanmh\Documents\R\win-library\3.2\strataG\libs\i386\strataG.dll: Permission denied
  Error: Command failed (1)

**Comment by bjcochrane** [comment]
Check your R version. If it's 3.11 or less dplyr won't load and the error results.

**Comment by smhoban** [comment]
Thanks Bruce!  Will do.

On Tue, Feb 16, 2016 at 3:20 PM, Bruce Cochrane notifications@github.com
wrote:

> Check your R version. If it's 3.11 or less dplyr won't load and the error
> results.
> 
> Sent from my iPhone
> 
> > On Feb 16, 2016, at 2:13 PM, Sean notifications@github.com wrote:
> > 
> > On windows I still get an error with 'dplyr'. Just FYI. I'll try on
> > ubuntu
> > 
> > *\* preparing package for lazy loading
> > Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()),
> > versionCheck = vI[[j]]) :
> > there is no package called 'dplyr'
> > Error : package 'apex' could not be loaded
> > ERROR: lazy loading failed for package 'strataG'
> > 
> > removing 'C:/Users/seanmh/Documents/R/win-library/3.2/strataG'
> > restoring previous 'C:/Users/seanmh/Documents/R/win-library/3.2/strataG'
> > Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date =
> > TRUE) : problem copying
> > C:\Users\seanmh\Documents\R\win-library\3.2\00LOCK-strataG\strataG\libs\i386\strataG.dll
> > to
> > C:\Users\seanmh\Documents\R\win-library\3.2\strataG\libs\i386\strataG.dll:
> > Permission denied Error: Command failed (1)
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/christianparobek/skeleSim/issues/18#issuecomment-184861284
> .

## 

Sean Hoban
Tree Conservation Biologist
The Morton Arboretum http://www.mortonarb.org/
4100 Illinois Rt 53, 3rd Floor Research Bldg, room 324, Lisle, IL
630-719-2419

## 

New publications!!
Accounting for the nested nature of genetic variation
http://onlinelibrary.wiley.com/doi/10.1111/oik.02760/abstract Oikos 2016
Exploring seaweed population dynamics
http://onlinelibrary.wiley.com/doi/10.1111/jpy.12366/abstract Journal of
Phycology 2016
Loci under selection in expanding tree populations
http://onlinelibrary.wiley.com/doi/10.1111/mec.13234/abstract Molecular
Ecology 2015
Designing optimal seed collection protocols
http://www.sciencedirect.com/science/article/pii/S0006320715001767
Biological Conservation 2015
Using ABC to understand invasive species establishment
http://www.nature.com/hdy/journal/vaop/ncurrent/full/hdy201538a.html
Heredity 2015

## 

research webpage: http://sites.google.com/site/hoban3/
ResearchGate Profile: http://www.researchgate.net/profile/Sean_Hoban/
food blog: http://cuisineraveclevin.blogspot.it/
blog about invasive species: http://invasivore.org/

**Comment by smhoban** [comment]
I think this is resolved
