### ISSUE TITLE
NOT CRITICAL skeleSim.old repository?

### ISSUE THREAD

**Issue by stranda** [christianparobek/skeleSim#19]
I'm wondering if we should create a skeleSim.old repository with all of the old, non-R-package code.  We can then 'promote' the contents of the skeleSim package up to the top-level of the repository.  

This suggestion would allow the use of the devtools function "install_github()" to install the package.  Right now you have to pull and then use the command line to install from a subdirectory.

cheers,
a.

**Comment by smhoban** [comment]
Sounds like a good idea to me

**Comment by smhoban** [comment]
Any downside to that suggestion?

**Comment by stranda** [comment]
1) spreading code around among repositories is a small issue I guess. 
2) additional complexity, there are alternatives to install_github; for example on the command line R CMD INSTALL or, I believe, there are some Rstudio buttons that can be pushed to accomplish the same goal, but I'm not exactly sure what they are

**Comment by EricArcher** [comment]
I like keeping everything in the same repository. We can still install the package with `install_github("christianparobek/skelesim/skelesim")`

Once we're ready to release, we should promote the package up a folder level and remove the archival code/miscellanea.
