### ISSUE TITLE
skeleSIM: meeting 1

### ISSUE THREAD

**Issue by liblig** [christianparobek/skeleSim#2]
Hi all – in order to schedule a time to chat this week, I suggest we use a doodle poll to select the Durham time/s that suit you to chat on skype. You’ll all receive an email invite shortly. Let’s be consistent and all communicate with reference to Durham time to avoid confusion. To find out what the time conversions are, and to understand the full spectrum of times we are working with, see [time buddy](http://www.worldtimebuddy.com). Select: Durham (=Charleston and Knoxville), Denver, San Diego, and Auckland. Yikes! Shall we aim to keep the meeting to 30mins, or an hour?

**Comment by christianparobek** [comment]
Thanks for organizing this Libby!
