### ISSUE TITLE
Testing analysis_funcs 2

### ISSUE THREAD

**Issue by MichelleDBG** [christianparobek/skeleSim#21]
Can someone take a look at 

data(woodmouse)
genes <- list(gene1=woodmouse[,1:500], gene2=woodmouse[,501:965])
x <- new("multidna", genes)
x.g <- sequence2gtypes(x)
strata(x.g) <- c("A", "B")

phist <- sapply(locNames(x.g), function(n) {
  unname(statPhist(x.g[, n, ]))
})
results_gtype

Why does "gene2" produce errors? 
fusFs(results_gtype[,2,])   

How could we skip over and have NA instead?

**Comment by EricArcher** [comment]
Sorry I've been incommunicado recently - I'm at a conference and my days and nights have been packed.
I vaguely remember this woodmouse data being a problem to use as an example, because I believe it doesn't have the same samples in the first gene as the second. You may have to create a better-behaved, more simulation-like toy sequence dataset to do your testing. If you don't have a solution by Sunday, let me know and I'll take a crack then.

**Comment by MichelleDBG** [comment]
I'm just trying this for now: 

# A DNAbin example that behaves maybe

data(woodmouse)
genes <- list(gene1=woodmouse[,1:400], gene2=woodmouse[,2:402])
x <- new("multidna", genes)
x.g <- sequence2gtypes(x)
strata(x.g) <- c("A", "B")
results_gtype <- x.g  

That is a good example of what will be in the params@rep.result slot, right? I still can't get skeleSim to fill that slot. Maybe it just takes longer than I'm letting it run.. (with fsc).

**Comment by MichelleDBG** [comment]
I will use nanacycats as an example for the genind object. However, why can't I create a new("skeleSim.params") object and then assign nanacycats or x.g or woodmouse to the @rep.result slot? 

Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “genind” is not valid for @‘rep.result’ in an object of class “skeleSim.params”; is(value, "intOrNum") is not TRUE

**Comment by EricArcher** [comment]
@rep.result holds the result from the analysis function and is defined to be an array of numbers. I think you want to put the genind object into @last.sample. The skelesim.classes.R file has definition of what the class slots are intended to be. Let me know if that works or if you're still running into problems.

**Comment by MichelleDBG** [comment]
Ah, if you mean @rep.sample instead of last (I don't see last.sample) then yes, that would be my problem. Thanks!!
