### ISSUE TITLE
first time running skeleSim GUI

### ISSUE THREAD

**Issue by smhoban** [christianparobek/skeleSim#22]
I followed the instructions here, and got through installing and loading skelesim (library) and that worked fine, but the command skeleSimGUI() results in:
Error: could not find function "skeleSimGUI"
Has it been renamed?

**Comment by stranda** [comment]
Hmm.  Should be able to (after Install):
library(skeleSim)
skeleSimGUI()

Works on my linux machine, I'm installing on windows now to check

**Comment by smhoban** [comment]
Same error on Ubuntu... 

install.packages("skeleSim_0.9.tar.gz")
library(skeleSim)
skeleSimGUI()
Error: could not find function "skeleSimGUI"

**Comment by stranda** [comment]
may be a version problem on ubuntu, can you try:
library(devtools)
install_github("christianparobek/skeleSim/skeleSim",force=T)

**Comment by smhoban** [comment]
I also managed to get this error.  Do I need the rmetasim from github?

Error : package 'rmetasim' 2.0.4 was found, but >= 3.0.0 is required by
'skeleSim'
ERROR: lazy loading failed for package 'skeleSim'

On Sun, Feb 21, 2016 at 5:09 PM, stranda notifications@github.com wrote:

> may be a version problem on ubuntu, can you try:
> library(devtools)
> install_github("christianparobek/skeleSim/skeleSim",force=T)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/christianparobek/skeleSim/issues/22#issuecomment-186928995
> .

## 

Sean Hoban
Tree Conservation Biologist
The Morton Arboretum http://www.mortonarb.org/
4100 Illinois Rt 53, 3rd Floor Research Bldg, room 324, Lisle, IL
630-719-2419

## 

New publications!!
Accounting for the nested nature of genetic variation
http://onlinelibrary.wiley.com/doi/10.1111/oik.02760/abstract Oikos 2016
Exploring seaweed population dynamics
http://onlinelibrary.wiley.com/doi/10.1111/jpy.12366/abstract Journal of
Phycology 2016
Loci under selection in expanding tree populations
http://onlinelibrary.wiley.com/doi/10.1111/mec.13234/abstract Molecular
Ecology 2015
Designing optimal seed collection protocols
http://www.sciencedirect.com/science/article/pii/S0006320715001767
Biological Conservation 2015
Using ABC to understand invasive species establishment
http://www.nature.com/hdy/journal/vaop/ncurrent/full/hdy201538a.html
Heredity 2015

## 

research webpage: http://sites.google.com/site/hoban3/
ResearchGate Profile: http://www.researchgate.net/profile/Sean_Hoban/
food blog: http://cuisineraveclevin.blogspot.it/
blog about invasive species: http://invasivore.org/

**Comment by stranda** [comment]
yeah, for the time being you have to install on ubuntu using install_github("stranda/rmetasim")

If you want to run on windows, I can email a windows binary as well

**Comment by smhoban** [comment]
Still the same error on ubuntu with the updated rmetasim.  I think it must
be I'm missing something with skelesim.  Is this the correct version of
skelesim: install.packages("skeleSim_0.9.tar.gz")

Where in the code is the function skeleSimGUI?

On Sun, Feb 21, 2016 at 2:20 PM, stranda notifications@github.com wrote:

> Hmm. Should be able to (after Install):
> library(skeleSim)
> skeleSimGUI()
> 
> Works on my linux machine, I'm installing on windows now to check
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/christianparobek/skeleSim/issues/22#issuecomment-186894203
> .

## 

Sean Hoban
Tree Conservation Biologist
The Morton Arboretum http://www.mortonarb.org/
4100 Illinois Rt 53, 3rd Floor Research Bldg, room 324, Lisle, IL
630-719-2419

## 

New publications!!
Accounting for the nested nature of genetic variation
http://onlinelibrary.wiley.com/doi/10.1111/oik.02760/abstract Oikos 2016
Exploring seaweed population dynamics
http://onlinelibrary.wiley.com/doi/10.1111/jpy.12366/abstract Journal of
Phycology 2016
Loci under selection in expanding tree populations
http://onlinelibrary.wiley.com/doi/10.1111/mec.13234/abstract Molecular
Ecology 2015
Designing optimal seed collection protocols
http://www.sciencedirect.com/science/article/pii/S0006320715001767
Biological Conservation 2015
Using ABC to understand invasive species establishment
http://www.nature.com/hdy/journal/vaop/ncurrent/full/hdy201538a.html
Heredity 2015

## 

research webpage: http://sites.google.com/site/hoban3/
ResearchGate Profile: http://www.researchgate.net/profile/Sean_Hoban/
food blog: http://cuisineraveclevin.blogspot.it/
blog about invasive species: http://invasivore.org/

**Comment by stranda** [comment]
I would definitely install the new version thats on github seems like you
have an old version of skeleSim

**Comment by EricArcher** [comment]
Heads-up: I'm in the middle of updating the fastsimcoal code, so it may break if you're using that simulator...

**Comment by smhoban** [comment]
skeleSimGUI() finally works on my new linux box!  The GUI opens and
everything is clickable.  I do get the following message in R though:

Note: the specification for S3 class “AsIs” in package ‘jsonlite’ seems
equivalent to one from package ‘RJSONIO’: not turning on duplicate class
definitions for this class.
Warning: Error in ssClassInit: object 'analysis_funcs' not found
Stack trace (innermost first):
    47: ssClassInit
[/home/user/R/x86_64-pc-linux-gnu-library/3.2/skeleSim/shiny/skeleSimShinyGUI/global.R#45]
    46: reactiveValues
    45: eval [serverInit.R#8]
    44: eval
    43: withVisible
    42: source
    41: server
[/home/user/R/x86_64-pc-linux-gnu-library/3.2/skeleSim/shiny/skeleSimShinyGUI/server.R#8]
     2: runApp
     1: skeleSimGUI
Error in ssClassInit() : object 'analysis_funcs' not found

On Mon, Feb 22, 2016 at 2:55 PM, Eric Archer notifications@github.com
wrote:

> Heads-up: I'm in the middle of updating the fastsimcoal code, so it may
> break if you're using that simulator...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/christianparobek/skeleSim/issues/22#issuecomment-187378688
> .

## 

Sean Hoban
Tree Conservation Biologist
The Morton Arboretum http://www.mortonarb.org/
4100 Illinois Rt 53, 3rd Floor Research Bldg, room 324, Lisle, IL
630-719-2419

## 

New publications!!
Accounting for the nested nature of genetic variation
http://onlinelibrary.wiley.com/doi/10.1111/oik.02760/abstract Oikos 2016
Exploring seaweed population dynamics
http://onlinelibrary.wiley.com/doi/10.1111/jpy.12366/abstract Journal of
Phycology 2016
Loci under selection in expanding tree populations
http://onlinelibrary.wiley.com/doi/10.1111/mec.13234/abstract Molecular
Ecology 2015
Designing optimal seed collection protocols
http://www.sciencedirect.com/science/article/pii/S0006320715001767
Biological Conservation 2015
Using ABC to understand invasive species establishment
http://www.nature.com/hdy/journal/vaop/ncurrent/full/hdy201538a.html
Heredity 2015

## 

research webpage: http://sites.google.com/site/hoban3/
ResearchGate Profile: http://www.researchgate.net/profile/Sean_Hoban/
food blog: http://cuisineraveclevin.blogspot.it/
blog about invasive species: http://invasivore.org/

**Comment by smhoban** [comment]
I think this is resolved
