### ISSUE TITLE
Multiple chromosomes? Multiple marker types?

### ISSUE THREAD

**Issue by EricArcher** [christianparobek/skeleSim#23]
I'm reformatting how loci are specified for fastsimcoal, and I want to clarify/remember a few things:

1) Are we allowing simulation of more than one chromosome? If so, how are we specifying recombination?

2) I believe we decided on allowing simulation of only one marker type (sequence, SNP, microsats) at a time, right? If so, I assume that we are allowing loci on the same chromosome with different parameters (e.g., multiple sets of microsatellite loci with different mutation rates)...

**Comment by smhoban** [comment]
I think its ok for now to assume either fully linked or fully independent
loci.  Specifying recombination could be tricky.  But that is my first
thought?

Yes I think we should allow different mutation rates.  It could be input in
the way that Allan allows allele frequencies to be input, which is nicely
dynamic

On Sun, Feb 21, 2016 at 11:41 PM, Eric Archer notifications@github.com
wrote:

> I'm reformatting how loci are specified for fastsimcoal, and I want to
> clarify/remember a few things:
> 
> 1) Are we allowing simulation of more than one chromosome? If so, how are
> we specifying recombination?
> 
> 2) I believe we decided on allowing simulation of only one marker type
> (sequence, SNP, microsats) at a time, right? If so, I assume that we are
> allowing loci on the same chromosome with different parameters (e.g.,
> multiple sets of microsatellite loci with different mutation rates)...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/christianparobek/skeleSim/issues/23.

## 

Sean Hoban
Tree Conservation Biologist
The Morton Arboretum http://www.mortonarb.org/
4100 Illinois Rt 53, 3rd Floor Research Bldg, room 324, Lisle, IL
630-719-2419

## 

New publications!!
Accounting for the nested nature of genetic variation
http://onlinelibrary.wiley.com/doi/10.1111/oik.02760/abstract Oikos 2016
Exploring seaweed population dynamics
http://onlinelibrary.wiley.com/doi/10.1111/jpy.12366/abstract Journal of
Phycology 2016
Loci under selection in expanding tree populations
http://onlinelibrary.wiley.com/doi/10.1111/mec.13234/abstract Molecular
Ecology 2015
Designing optimal seed collection protocols
http://www.sciencedirect.com/science/article/pii/S0006320715001767
Biological Conservation 2015
Using ABC to understand invasive species establishment
http://www.nature.com/hdy/journal/vaop/ncurrent/full/hdy201538a.html
Heredity 2015

## 

research webpage: http://sites.google.com/site/hoban3/
ResearchGate Profile: http://www.researchgate.net/profile/Sean_Hoban/
food blog: http://cuisineraveclevin.blogspot.it/
blog about invasive species: http://invasivore.org/

**Comment by EricArcher** [comment]
Sounds good. I've now set the fastsimcoal code so that only one type of marker (dna, msat, or snp) can be simulated, but multiple loci (stretches of sequence, msat, or snp loci) can be simulated on a single chromosome as well as across multiple chromosomes.
