### ISSUE TITLE
Number of permutation test replicates

### ISSUE THREAD

**Issue by EricArcher** [christianparobek/skeleSim#24]
When I'm doing a standard population structure test (Fst, PHIst, etc), I typically don't do more than 1000 replicates to estimate the p-value. My rationale is that I'm usually interested in evaluating out to the 100ths place (e.g., p < 0.05), so I only need precision to the 1000ths place (p = 0.051 vs. p = 0.049).
If the user is interested in calculating p-values for these tests (not all will be), I'm wondering if we can a) put a cap on the number of permutation replicates in skeleSim, and b) if so, what it should be. If they are interested in the p-values, what they're getting back is a distribution, and I'm not sure in that case that precision to the 1000ths place will be as necessary. Since we're looking at a lot of stats over potentially many individuals for a lot of replicates, the ten-fold difference between 100 and 1000 replicates can add up.

Thoughts?

**Comment by smhoban** [comment]
I would agree on doing 100- I think that works good.

On Sat, Feb 27, 2016 at 8:19 PM, Eric Archer notifications@github.com
wrote:

> When I'm doing a standard population structure test (Fst, PHIst, etc), I
> typically don't do more than 1000 replicates to estimate the p-value. My
> rationale is that I'm usually interested in evaluating out to the 100ths
> place (e.g., p < 0.05), so I only need precision to the 1000ths place (p =
> 0.051 vs. p = 0.049).
> If the user is interested in calculating p-values for these tests (not all
> will be), I'm wondering if we can a) put a cap on the number of permutation
> replicates in skeleSim, and b) if so, what it should be. If they are
> interested in the p-values, what they're getting back is a distribution,
> and I'm not sure in that case that precision to the 1000ths place will be
> as necessary. Since we're looking at a lot of stats over potentially many
> individuals for a lot of replicates, the ten-fold difference between 100
> and 1000 replicates can add up.
> 
> Thoughts?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/christianparobek/skeleSim/issues/24.

## 

Sean Hoban
Tree Conservation Biologist
The Morton Arboretum http://www.mortonarb.org/
4100 Illinois Rt 53, 3rd Floor Research Bldg, room 324, Lisle, IL
630-719-2419

## 

New publications!!
Accounting for the nested nature of genetic variation
http://onlinelibrary.wiley.com/doi/10.1111/oik.02760/abstract Oikos 2016
Exploring seaweed population dynamics
http://onlinelibrary.wiley.com/doi/10.1111/jpy.12366/abstract Journal of
Phycology 2016
Loci under selection in expanding tree populations
http://onlinelibrary.wiley.com/doi/10.1111/mec.13234/abstract Molecular
Ecology 2015
Designing optimal seed collection protocols
http://www.sciencedirect.com/science/article/pii/S0006320715001767
Biological Conservation 2015
Using ABC to understand invasive species establishment
http://www.nature.com/hdy/journal/vaop/ncurrent/full/hdy201538a.html
Heredity 2015

## 

research webpage: http://sites.google.com/site/hoban3/
ResearchGate Profile: http://www.researchgate.net/profile/Sean_Hoban/
food blog: http://cuisineraveclevin.blogspot.it/
blog about invasive species: http://invasivore.org/

**Comment by stranda** [comment]
I'll update the UI default to 100 reps
