### ISSUE TITLE
Bugs while running

### ISSUE THREAD

**Issue by smhoban** [christianparobek/skeleSim#25]
Thanks for squashing the bug I mentioned last week with "analysis_funcs".  No problems there now.

New error.  When I go to "General Conf" and click "Coalescent simulator?" checkbox I get: 

Warning: Error in observeEventHandler: no slot of name "inf.site.model" for this object of class "fastsimcoal.params"
Stack trace (innermost first):
    64: observeEventHandler [make-skelesim-class.R#262]
     2: runApp
     1: skeleSimGUI
[1] "numloci 1"
Warning: Error in <Anonymous>: assignment of an object of class “matrix” is not valid for @‘locus.params’ in an object of class “fastsimcoal.params”; is(value, "dfOrNULL") is not TRUE
Stack trace (innermost first):
    65: <Anonymous>
    64: observeEventHandler [simcoal-server.R#131]
     2: runApp
     1: skeleSimGUI
Warning: Error in observeEventHandler: no slot of name "inf.site.model" for this object of class "fastsimcoal.params"
Stack trace (innermost first):
    64: observeEventHandler [make-skelesim-class.R#262]
     2: runApp
     1: skeleSimGUI

**Comment by EricArcher** [comment]
This is due to the new fastsimcoal input format. It is now a data.frame where before it was a matrix. The columns are also somewhat different.

Also, the slot, "inf.site.model" has been removed.

**Comment by smhoban** [comment]
Thanks.  All: I'm finding various ways to break skelesim or various
questions or quirks as I go through the user guide.  These are going in one
issue (#26) for now.  Nothing urgent but some things to work on.

On Mon, Mar 7, 2016 at 9:52 AM, Eric Archer notifications@github.com
wrote:

> This is due to the new fastsimcoal input format. It is now a data.frame
> where before it was a matrix. The columns are also somewhat different.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/christianparobek/skeleSim/issues/25#issuecomment-193311330
> .

## 

Sean Hoban
Tree Conservation Biologist
The Morton Arboretum http://www.mortonarb.org/
4100 Illinois Rt 53, 3rd Floor Research Bldg, room 324, Lisle, IL
630-719-2419

## 

New publications!!
Accounting for the nested nature of genetic variation
http://onlinelibrary.wiley.com/doi/10.1111/oik.02760/abstract Oikos 2016
Exploring seaweed population dynamics
http://onlinelibrary.wiley.com/doi/10.1111/jpy.12366/abstract Journal of
Phycology 2016
Loci under selection in expanding tree populations
http://onlinelibrary.wiley.com/doi/10.1111/mec.13234/abstract Molecular
Ecology 2015
Designing optimal seed collection protocols
http://www.sciencedirect.com/science/article/pii/S0006320715001767
Biological Conservation 2015
Using ABC to understand invasive species establishment
http://www.nature.com/hdy/journal/vaop/ncurrent/full/hdy201538a.html
Heredity 2015

## 

research webpage: http://sites.google.com/site/hoban3/
ResearchGate Profile: http://www.researchgate.net/profile/Sean_Hoban/
food blog: http://cuisineraveclevin.blogspot.it/
blog about invasive species: http://invasivore.org/

**Comment by smhoban** [comment]
Lastly, I might be missing out on something but now that I've got my test skelesim object prepared, with two scenarios, I click "Run simulation" and nothing happens.  Well, I get "Wrote skeleSim parameter file: '/home/user/Documents/test.20160308.1230.6079.params.rdata'" but this just has my skelesim object but no results.

Can someone try to load this object and run it, and tell me what I'm missing :)  I'll put this object in the main directory:    test.20160308.1226.2546.params.rdata

**Comment by smhoban** [comment]
Now I've pulled everything and I get the following error which I didn't get before: 

Note: the specification for S3 class “AsIs” in package ‘jsonlite’ seems equivalent to one from package ‘RJSONIO’: not turning on duplicate class definitions for this class.
Warning: Error in is.data.frame: object 'result' not found
Stack trace (innermost first):
    49: is.data.frame
    48: colnames
    47: match
    46: %in%
    45: eval [visualize.R#26]
    44: eval
    43: withVisible
    42: source
    41: server [/home/user/R/x86_64-pc-linux-gnu-library/3.2/skeleSim/shiny/skeleSimShinyGUI/server.R#53]
     2: runApp
     1: skeleSimGUI
Error in is.data.frame(x) : object 'result' not found

**Comment by MichelleDBG** [comment]
How about this error (after "Coalescent simulator" is selected)

Warning: Error in observeEventHandler: no slot of name "inf.site.model" for this object of class "fastsimcoal.params"
Stack trace (innermost first):
    64: observeEventHandler [make-skelesim-class.R#262]
     2: runApp
     1: skeleSimGUI
[1] "numloci 1"
Warning: Error in <Anonymous>: assignment of an object of class “matrix” is not valid for @‘locus.params’ in an object of class “fastsimcoal.params”; is(value, "dfOrNULL") is not TRUE
Stack trace (innermost first):
    65: <Anonymous>
    64: observeEventHandler [simcoal-server.R#131]
     2: runApp
     1: skeleSimGUI
Warning: Error in observeEventHandler: no slot of name "inf.site.model" for this object of class "fastsimcoal.params"
Stack trace (innermost first):
    64: observeEventHandler [make-skelesim-class.R#262]
     2: runApp
     1: skeleSimGUI
[1] "numloci 1"
Warning: Error in <Anonymous>: assignment of an object of class “matrix” is not valid for @‘locus.params’ in an object of class “fastsimcoal.params”; is(value, "dfOrNULL") is not TRUE
Stack trace (innermost first):
    65: <Anonymous>
    64: observeEventHandler [simcoal-server.R#131]
     2: runApp
     1: skeleSimGUI
ERROR: [on_request_read] connection reset by peer

**Comment by smhoban** [comment]
Me too!  I think Allan was chasing this one..

On Thu, Mar 10, 2016 at 2:45 PM, Michelle DePrenger-Levin <
notifications@github.com> wrote:

> How about this error (after "Coalescent simulator" is selected)
> 
> Warning: Error in observeEventHandler: no slot of name "inf.site.model"
> for this object of class "fastsimcoal.params"
> Stack trace (innermost first):
> 64: observeEventHandler [make-skelesim-class.R#262]
> 2: runApp
> 1: skeleSimGUI
> [1] "numloci 1"
> Warning: Error in : assignment of an object of class “matrix” is not valid
> for @‘locus.params’ in an object of class “fastsimcoal.params”; is(value,
> "dfOrNULL") is not TRUE
> Stack trace (innermost first):
> 65:
> 64: observeEventHandler [simcoal-server.R#131]
> 2: runApp
> 1: skeleSimGUI
> Warning: Error in observeEventHandler: no slot of name "inf.site.model"
> for this object of class "fastsimcoal.params"
> Stack trace (innermost first):
> 64: observeEventHandler [make-skelesim-class.R#262]
> 2: runApp
> 1: skeleSimGUI
> [1] "numloci 1"
> Warning: Error in : assignment of an object of class “matrix” is not valid
> for @‘locus.params’ in an object of class “fastsimcoal.params”; is(value,
> "dfOrNULL") is not TRUE
> Stack trace (innermost first):
> 65:
> 64: observeEventHandler [simcoal-server.R#131]
> 2: runApp
> 1: skeleSimGUI
> ERROR: [on_request_read] connection reset by peer
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/christianparobek/skeleSim/issues/25#issuecomment-195038840
> .

## 

Sean Hoban
Tree Conservation Biologist
The Morton Arboretum http://www.mortonarb.org/
4100 Illinois Rt 53, 3rd Floor Research Bldg, room 324, Lisle, IL
630-719-2419

## 

New publications!!
Accounting for the nested nature of genetic variation
http://onlinelibrary.wiley.com/doi/10.1111/oik.02760/abstract Oikos 2016
Exploring seaweed population dynamics
http://onlinelibrary.wiley.com/doi/10.1111/jpy.12366/abstract Journal of
Phycology 2016
Loci under selection in expanding tree populations
http://onlinelibrary.wiley.com/doi/10.1111/mec.13234/abstract Molecular
Ecology 2015
Designing optimal seed collection protocols
http://www.sciencedirect.com/science/article/pii/S0006320715001767
Biological Conservation 2015
Using ABC to understand invasive species establishment
http://www.nature.com/hdy/journal/vaop/ncurrent/full/hdy201538a.html
Heredity 2015

## 

research webpage: http://sites.google.com/site/hoban3/
ResearchGate Profile: http://www.researchgate.net/profile/Sean_Hoban/
food blog: http://cuisineraveclevin.blogspot.it/
blog about invasive species: http://invasivore.org/

**Comment by smhoban** [comment]
I'm still getting the same error that Michelle and I got (above) when we click on 'coalescent simulation'.  This is a pretty big one because you can't get past it and so can't do any coalescent simulations- the whole system crashes. Anyone on this one?

**Comment by stranda** [comment]
Ok Now I see that Eric had already removed int.site.model on purpose.  It is now removed from the ui.  I still have growth rates and sample times re-added.  Do I need to remove those inputs from the ui as well?

**Comment by smhoban** [comment]
Works for me now.  Anyway I can click on coalescent without crashing it.  So that is a start!

**Comment by EricArcher** [comment]
Sorry I'm getting to this late. You guys have nailed the cause. Allan, growth rates and sample times are input as part of the single fsc.loadScenario function now. Let me know if you've got other questions on that.

**Comment by stranda** [comment]
I think this one is closed
