### ISSUE TITLE
Questions while running GUI

### ISSUE THREAD

**Issue by smhoban** [christianparobek/skeleSim#26]
Question 1: how is the "Select Simulation Root Directory" on tab 1 different from the "Subdirectory for actual simulation" on tab 3?

**Comment by smhoban** [comment]
Question 2: A small thing, but on this screen of the GUI: https://github.com/christianparobek/skeleSim/blob/master/doc/scenario-1.png

Within this main tab of all the parameters, we've got the 3 sub tabs going left to right: "Population characteristics," "Among population migration rate" and "Locus characteristics".  But on the left we've got these a little out of order from top to bottom- they go "population stuff", "locus stuff", "migration stuff".  Can we just shift the order of those on the left to be "population stuff", "migration stuff", "locus stuff".  It'll be easier to explain in the vignette if these go in order.

**Comment by smhoban** [comment]
Question 3: When doing the rmetasim locus details, I can't define the full allele frequency distribution?  I click on radio button this and nothing happens.  

Also if I try the plus/minus buttons here it all crashes with this error: 
Warning: Error in rep: invalid 'times' argument
Stack trace (innermost first):
    66: FUN [rmetasim-server.R#76]
    65: lapply [rmetasim-server.R#76]
    64: observeEventHandler [rmetasim-server.R#76]
     2: runApp
     1: skeleSimGUI

**Comment by smhoban** [comment]
Another way to break it...  On the tab "Scenario Conf" if I accidentally click "scenario number" down arrow to 0 or less, it all crashes.  Obviously you can't have a scenario 0 or -1, but it shouldn't crash, so a catch is needed here.  This is the trace:

Warning: Error in [[: attempt to select less than one element
Stack trace (innermost first):
    69: reactive hst [simcoal-server.R#14]
    58: hst
    57: observeEventExpr
     2: runApp
     1: skeleSimGUI
Warning: Error in [[: attempt to select less than one element
Stack trace (innermost first):
    57: observeEventExpr
     2: runApp
     1: skeleSimGUI

**Comment by smhoban** [comment]
Lastly, I might be missing out on something but now that I've got my test skelesim object prepared, with two scenarios, I click "Run simulation" and nothing happens. Well, I get "Wrote skeleSim parameter file: '/home/user/Documents/test.20160308.1230.6079.params.rdata'" but this just has my skelesim object but no results.

Can someone try to load this object and run it, and tell me what I'm missing :) I'll put this object in the main directory: test.20160308.1226.2546.params.rdata

**Comment by MichelleDBG** [comment]
Sean - I'm following your workflow and I can't get shiny to let me change the population sizes within the boxes in Scenario Conf/Population characteristics. You have this problem before?

**Comment by smhoban** [comment]
I am able to change them.  It takes couple clicks sometimes not sure why
but eventually it lets me :)

It won't let you change migration rates unless you click "user defined"

On Wed, Mar 9, 2016 at 1:08 PM, Michelle DePrenger-Levin <
notifications@github.com> wrote:

> Sean - I'm following your workflow and I can't get shiny to let me change
> the population sizes within the boxes in Scenario Conf/Population
> characteristics. You have this problem before?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/christianparobek/skeleSim/issues/26#issuecomment-194456338
> .

## 

Sean Hoban
Tree Conservation Biologist
The Morton Arboretum http://www.mortonarb.org/
4100 Illinois Rt 53, 3rd Floor Research Bldg, room 324, Lisle, IL
630-719-2419

## 

New publications!!
Accounting for the nested nature of genetic variation
http://onlinelibrary.wiley.com/doi/10.1111/oik.02760/abstract Oikos 2016
Exploring seaweed population dynamics
http://onlinelibrary.wiley.com/doi/10.1111/jpy.12366/abstract Journal of
Phycology 2016
Loci under selection in expanding tree populations
http://onlinelibrary.wiley.com/doi/10.1111/mec.13234/abstract Molecular
Ecology 2015
Designing optimal seed collection protocols
http://www.sciencedirect.com/science/article/pii/S0006320715001767
Biological Conservation 2015
Using ABC to understand invasive species establishment
http://www.nature.com/hdy/journal/vaop/ncurrent/full/hdy201538a.html
Heredity 2015

## 

research webpage: http://sites.google.com/site/hoban3/
ResearchGate Profile: http://www.researchgate.net/profile/Sean_Hoban/
food blog: http://cuisineraveclevin.blogspot.it/
blog about invasive species: http://invasivore.org/

**Comment by stranda** [comment]
Try highlighting the rate and typing in a new one.  Should not depend on user defined migration

**Comment by MichelleDBG** [comment]
Yaarggg, I can't change any numbers in any of the internal tab boxes. I'll go through and see if something needs updating...

**Comment by smhoban** [comment]
Maybe a shiney thing then?

On Wed, Mar 9, 2016 at 1:40 PM, Michelle DePrenger-Levin <
notifications@github.com> wrote:

> Yaarggg, I can't change any numbers in any of the internal tab boxes. I'll
> go through and see if something needs updating...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/christianparobek/skeleSim/issues/26#issuecomment-194472233
> .

## 

Sean Hoban
Tree Conservation Biologist
The Morton Arboretum http://www.mortonarb.org/
4100 Illinois Rt 53, 3rd Floor Research Bldg, room 324, Lisle, IL
630-719-2419

## 

New publications!!
Accounting for the nested nature of genetic variation
http://onlinelibrary.wiley.com/doi/10.1111/oik.02760/abstract Oikos 2016
Exploring seaweed population dynamics
http://onlinelibrary.wiley.com/doi/10.1111/jpy.12366/abstract Journal of
Phycology 2016
Loci under selection in expanding tree populations
http://onlinelibrary.wiley.com/doi/10.1111/mec.13234/abstract Molecular
Ecology 2015
Designing optimal seed collection protocols
http://www.sciencedirect.com/science/article/pii/S0006320715001767
Biological Conservation 2015
Using ABC to understand invasive species establishment
http://www.nature.com/hdy/journal/vaop/ncurrent/full/hdy201538a.html
Heredity 2015

## 

research webpage: http://sites.google.com/site/hoban3/
ResearchGate Profile: http://www.researchgate.net/profile/Sean_Hoban/
food blog: http://cuisineraveclevin.blogspot.it/
blog about invasive species: http://invasivore.org/

**Comment by MichelleDBG** [comment]
Ha ha! updated shiny and now I can add text.

**Comment by MichelleDBG** [comment]
I enter 0 for each migration matrix and it recalculates with 1s. I tried changing the distance function and slipped on dexp. Now I don't have any other options in that drop down and can only get three zeros and one 1.

**Comment by smhoban** [comment]
Hmm under migration model I could choose 'user' and that worked

On Wed, Mar 9, 2016 at 2:05 PM, Michelle DePrenger-Levin <
notifications@github.com> wrote:

> I enter 0 for each migration matrix and it recalculates with 1s. I tried
> changing the distance function and slipped on dexp. Now I don't have any
> other options in that drop down and can only get three zeros and one 1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/christianparobek/skeleSim/issues/26#issuecomment-194481649
> .

## 

Sean Hoban
Tree Conservation Biologist
The Morton Arboretum http://www.mortonarb.org/
4100 Illinois Rt 53, 3rd Floor Research Bldg, room 324, Lisle, IL
630-719-2419

## 

New publications!!
Accounting for the nested nature of genetic variation
http://onlinelibrary.wiley.com/doi/10.1111/oik.02760/abstract Oikos 2016
Exploring seaweed population dynamics
http://onlinelibrary.wiley.com/doi/10.1111/jpy.12366/abstract Journal of
Phycology 2016
Loci under selection in expanding tree populations
http://onlinelibrary.wiley.com/doi/10.1111/mec.13234/abstract Molecular
Ecology 2015
Designing optimal seed collection protocols
http://www.sciencedirect.com/science/article/pii/S0006320715001767
Biological Conservation 2015
Using ABC to understand invasive species establishment
http://www.nature.com/hdy/journal/vaop/ncurrent/full/hdy201538a.html
Heredity 2015

## 

research webpage: http://sites.google.com/site/hoban3/
ResearchGate Profile: http://www.researchgate.net/profile/Sean_Hoban/
food blog: http://cuisineraveclevin.blogspot.it/
blog about invasive species: http://invasivore.org/

**Comment by stranda** [comment]
Right...I misunderstood.  The elements in the matrix can only be changed under "user" migration model.  I thought you were talking about the migration multiplier on the left hand column.  It gets multiplied throughout the migration matrix

**Comment by stranda** [comment]
I think that I have addressed the issues raised here.
