### ISSUE TITLE
shinyFiles dependency

### ISSUE THREAD

**Issue by christianparobek** [christianparobek/skeleSim#27]
Just pulled the new version of shiny `server.R` and `ui.R`. When I got to "Run App" it gives a new error - something to the effect of:

```
unknown function: shinyFilesButton()
```

I solved this by installing the `shinyFiles` package and loading it up with `library()`. But it seems like perhaps `shinyFiles` should now be a dependency upon install?

**Comment by EricArcher** [comment]
Definitely sounds like it. Good catch! Please add it to the dependency list in DESCRIPTION.

**Comment by christianparobek** [comment]
Interesting, I just checked the Depends list in the DESCRIPTION file and it's already in there. Maybe I did something wrong this morning? I started with a fresh `github_install` of skeleSim as well as updating my local repo with a `pull`. Could it be that it belongs in the Imports list instead?

**Comment by EricArcher** [comment]
Hmmm... the default for install_github seems to be to install dependencies listed in "Depends". Can you test by uninstalling other packages in Depends (like shiny) and reinstalling from GitHub to see if it actually does?

**Comment by stranda** [comment]
Has this one been resolved?

**Comment by christianparobek** [comment]
Yes, this was resolved.

**Comment by christianparobek** [comment]
This dependency has actually still been giving me problems off and on for a while. Today, I did a fresh install from github `install_github("christianparobek/skeleSim")` on three different computers: two Ubuntus and one Windows, and in each case I got this same error:

```
ERROR: could not find function "shinyFilesButton"
```

Two of these computers never had seen `skeleSim` before. Took a look at the DESCRIPTION file and shinyFiles isn't under the Depends section... odd. Trying to add that and will see if that fixes it.

**Comment by christianparobek** [comment]
This seems to fix it on all three computers.

**Comment by christianparobek** [comment]
Hope my fix doesn't mess anything else up!

**Comment by EricArcher** [comment]
I'd removed it from Depends and was looking to add it to Imports and add the appropriate @importFrom roxygen tags. Putting it back in Depends is fine for now. I'm still working on some build/check issues, but will come back to this later.
