### ISSUE TITLE
Questions for Case studies for sim... vignette

### ISSUE THREAD

**Issue by MichelleDBG** [christianparobek/skeleSim#29]
How does someone look at the skeleSim object? Typing what into R? Do you have to exit out of the shiny first? Do you just mean looking at the "Current ssClass"? That only shows the current simulation. I'd want to put a code chunk in the vignette of what to type in to see the skeleSim object.

**Comment by smhoban** [comment]
Good question!  I was thinking the Current ssClass.  This shows all the scenarios and I think the whole object.  What are you looking to see?

**Comment by MichelleDBG** [comment]
I was thinking we'd want to tell people how to call the skeleSim object in the R console so someone could get the data and do whatever they wanted with it.

**Comment by smhoban** [comment]
Yepp that is important!  I don't know how to call it, other than to save it using the GUI and then loading that workspace?

**Comment by smhoban** [comment]
Typing in ssClass in R should do it
