### ISSUE TITLE
Workflow/Parameter list

### ISSUE THREAD

**Issue by EricArcher** [christianparobek/skeleSim#3]
1. Reason for simulation: (n)ull model, (p)erformance test, (m)anagement, (e)stimate parameters
2. Type of simulator: (c)oalescent, (f)orward-time
3. Parameters
   - skeleSim.params@title
   - skeleSim.params@date
   - skeleSim.params@param.check.func
   - skeleSim.params@sim.func
   - skeleSim.params@rep.analysis.func
   - skeleSim.params@sim.summary.func
   - skeleSim.params@last.sample
   - skeleSim.params@last.result
   - skeleSim.params@analysis.results
   - skeleSim@scenarios: a list of scenario.params class objects
     - skeleSim.params@scenarios@num.pops
     - skeleSim.params@scenarios@pop.size
     - skeleSim.params@scenarios@sample.size
     - skeleSim.params@scenarios@migration
     - skeleSim.params@scenarios@simulator.params: simulator-specific parameters. Can be own class or just list
4. Parameter check (@param.check.func)
5. Timing check
6. Run simulation
   - Run one replicate (@sim.func)
   - Analyze results (@rep.analysis.func)
7. Sumarize simulation (@sim.summary.func)
   - Display plots
   - Display summary tables
### Notes
- All skeleSim core functions accept and return a skeleSim.params object ('params')

**Comment by smhoban** [comment]
This is great!

Regarding plots and summary tables, right now the functionality is to display all possible plots, which could be dozens (or more, depending on number of populations).  I presume the user will also want to interact with this, i.e. to choose to display/ print one or a few statistics at a time?  If so, we will need some interaction around number 7.

**Comment by EricArcher** [comment]
You're right Sean. I think this flow is the skeleton of skeleSim and there will likely be interaction at each point. The interface will probably be the hardest part of this. If we can get it Shiny-fied, our lives will be a lot easier.

I just got back from travel and will start trying to put together the framework for identifying slots in the params class that need to be filled and applying the right questions. Hopefully we'll be able to implement that in a non-Shiny world, but it will also serve us once Christian has us up and running (no pressure!)
