### ISSUE TITLE
new pop.info  paramter

### ISSUE THREAD

**Issue by stranda** [christianparobek/skeleSim#30]
Hey Folks, 
I think this one is for Eric. 

No doubt I have been told this but, I finally figured out that pop.info is supposed to contain the information we have been storing in popsize growth.rate, etc...I can convert to this form in the ui, but I need a little more information about the how the structure of the pop.info matrix should look.

**Comment by stranda** [comment]
I took a look at the strataG function and now understand the structure of the matrix.  This might take a while to make sure I wrap and unwrap properly from the format I've been using in the UI

**Comment by EricArcher** [comment]
Allan,

I don't know how deep you are into this, but if a different interface/format for loading fastsimcoal parameters from shiny is easier for you, I can implement that. For instance, would it help if I made pop.info, hist.ev, and locus.params classes with slots you could fill directly? I could also make it read from a simple list with named elements. Whatever is easiest for you to load and read from shiny...

**Comment by stranda** [comment]
I haven't done anything with it yet, but I have a plan.  I don't think you
need to do anything now that I understand the problem
cheers,
a.

**Comment by EricArcher** [comment]
Cool. If your plan gets sticky, give me a holler and I can help ease the pain.

**Comment by stranda** [comment]
thanks,
a.
