### ISSUE TITLE
Quick questions simcoal GUI interface 1

### ISSUE THREAD

**Issue by smhoban** [christianparobek/skeleSim#31]
Question:

I can't interact with the simcoal coalescent diagram (in the GUI FastSimcoal params, Simcoal History)- I click on the arrows but nothing happens.  Is this just me?  Am I having shiney issues?

**Comment by stranda** [comment]
click once on the source population anywhere above the x-position of that
population.  Then  double-click on the sink population at the time depth
coalescence should occur
cheers,
a.

On Thu, Mar 17, 2016 at 10:46 AM, Sean notifications@github.com wrote:

> Question:
> 
> I can't interact with the simcoal coalescent diagram (in the GUI
> FastSimcoal params, Simcoal History)- I click on the arrows but nothing
> happens. Is this just me? Am I having shiney issues?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/christianparobek/skeleSim/issues/31

## 

Allan Strand,   Biology    http://linum.cofc.edu
College of Charleston      Ph. (843) 953-9189
Charleston, SC 29424     Fax (843) 953-9199

**Comment by smhoban** [comment]
Ok yepp.  I should have read instructions!

On Thu, Mar 17, 2016 at 1:56 PM, stranda notifications@github.com wrote:

> click once on the source population anywhere above the x-position of that
> population. Then double-click on the sink population at the time depth
> coalescence should occur
> cheers,
> a.
> 
> On Thu, Mar 17, 2016 at 10:46 AM, Sean notifications@github.com wrote:
> 
> > Question:
> > 
> > I can't interact with the simcoal coalescent diagram (in the GUI
> > FastSimcoal params, Simcoal History)- I click on the arrows but nothing
> > happens. Is this just me? Am I having shiney issues?
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/christianparobek/skeleSim/issues/31
> 
> ## 
> 
> Allan Strand, Biology http://linum.cofc.edu
> College of Charleston Ph. (843) 953-9189
> Charleston, SC 29424 Fax (843) 953-9199
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/christianparobek/skeleSim/issues/31#issuecomment-198033612

## 

Sean Hoban
Tree Conservation Biologist
The Morton Arboretum http://www.mortonarb.org/
4100 Illinois Rt 53, 3rd Floor Research Bldg, room 324, Lisle, IL
630-719-2419

## 

New publications!!
Accounting for the nested nature of genetic variation
http://onlinelibrary.wiley.com/doi/10.1111/oik.02760/abstract Oikos 2016
Exploring seaweed population dynamics
http://onlinelibrary.wiley.com/doi/10.1111/jpy.12366/abstract Journal of
Phycology 2016
Loci under selection in expanding tree populations
http://onlinelibrary.wiley.com/doi/10.1111/mec.13234/abstract Molecular
Ecology 2015
Designing optimal seed collection protocols
http://www.sciencedirect.com/science/article/pii/S0006320715001767
Biological Conservation 2015
Using ABC to understand invasive species establishment
http://www.nature.com/hdy/journal/vaop/ncurrent/full/hdy201538a.html
Heredity 2015

## 

research webpage: http://sites.google.com/site/hoban3/
ResearchGate Profile: http://www.researchgate.net/profile/Sean_Hoban/
food blog: http://cuisineraveclevin.blogspot.it/
blog about invasive species: http://invasivore.org/

**Comment by smhoban** [comment]
Yepp, that works!
