### ISSUE TITLE
Quick questions simcoal GUI interface- migration

### ISSUE THREAD

**Issue by smhoban** [christianparobek/skeleSim#32]
General question- at each historical event in simcoal, when making a par file, you can usually define a new migration matrix (with all new migration rates).  I guess we haven't implemented this in the GUI yet?  i didn't see a place to add a second migration matrix (within a scenario)

**Comment by EricArcher** [comment]
I don't think Allan has implemented this in shiny. The fastsimcoal interface through strataG and the skelesim fsc.loadParameters function will accept a list of migration matrices though, so people creating a skelesim params object on the command line can do this. I'd say we leave this for a v1.2 release.

**Comment by stranda** [comment]
Eric's right, I have not implemented now.  We only have a constant
migration matrix  possible at the moment.  I like the idea of a v1.2 release
a.

On Thu, Mar 17, 2016 at 10:54 AM, Eric Archer notifications@github.com
wrote:

> I don't think Allan has implemented this in shiny. The fastsimcoal
> interface through strataG and the skelesim fsc.loadParameters function will
> accept a list of migration matrices though, so people creating a skelesim
> params object on the command line can do this. I'd say we leave this for a
> v1.2 release.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/christianparobek/skeleSim/issues/32#issuecomment-197916073

## 

Allan Strand,   Biology    http://linum.cofc.edu
College of Charleston      Ph. (843) 953-9189
Charleston, SC 29424     Fax (843) 953-9199

**Comment by stranda** [comment]
Now this works.  Specify as many migration matrices as needed (there is a counter right above the matrix input).  They are indexed from 0 and can be referenced in the migration matrix
