### ISSUE TITLE
Fresh skeleSim install - markdown needs separate install?

### ISSUE THREAD

**Issue by EricArcher** [christianparobek/skeleSim#34]
I've just successfully installed and initiated skeleSim from GitHub on a Windows machine that has never seen it, and had a fresh R install with only devtools installed on top of base packages. I had to first install strataG and rmetasim from GitHub. When I then tried to install skeleSim, I got an error about missing the markdown package. I couldn't figure out if this was due to skeleSim needing it directly or one of its dependencies. I installed markdown, then did a reinstall of skeleSim and it worked to completion. 

I updated the Imports list in DESCRIPTION to include markdown and will try later to see if this solves the problem. I tried a CRAN check and it complains that skeleSim does not explicitly import from markdown, so we'll have to work this issue out at some point before submission to CRAN.

**Comment by stranda** [comment]
thanks Eric,
I use markdown files as help files in the shiny interface, so it is a "primary dependency" I guess.  Will add to the list.
cheers,
a.

**Comment by EricArcher** [comment]
I've moved markdown to the Depends: section. Should work now.
