### ISSUE TITLE
Historical event specification bugs

### ISSUE THREAD

**Issue by EricArcher** [christianparobek/skeleSim#35]
1) The historical event tab, seems to have some default values (two events) already specified. Was this just for testing?

2) Modifying source or sink demes seems to change the the time value in the first column for other events.

3) I tried to add a new event, but when I went back to modify another event, the event was deleted.

**Comment by stranda** [comment]
These are working on my linux setup. There are times when the history matrix rows are sorted by time, but this does not change any entries, just the row order.

I'm installing on a windows VM to test there.  I'm also re-pushing to make sure that I haven't forgotten anything.

I _have_ disabled the ability to change history by point and click.  it was creating non-compliant history matrices occasionally.  Once I'm comfortable with a fix, I'll turn it back on.

**Comment by stranda** [comment]
I did find a related bug and squashed it.  Still leaving this issue open.

**Comment by stranda** [comment]
This one is fixed, though there is no point and click history selection at the moment
