### ISSUE TITLE
Set temp working directory to title

### ISSUE THREAD

**Issue by EricArcher** [christianparobek/skeleSim#36]
The temporary working directory seems to default to "wdTest". Would it be better to set it to the Title (change it when Title is changed), but let a user modify it if they choose?

**Comment by stranda** [comment]
I think that should be possible.  Will take a look Wed am.

**Comment by MichelleDBG** [comment]
Does the user need to add the path or will it either make a new folder called "wdTest" or a folder named whatever Title the user puts in or is this the Rdata file? That temporary working directory confuses me.

**Comment by stranda** [comment]
The user just needs to specify the folder in which a simulation's inputs
and outputs will reside.  When the simulations run, the wdTest folder gets
created to hold temporary files.  Unless there's a problem with the
simulations, you can usually ignore its contents. The 'simulations'
vignette also has some copy describing this setup
