### ISSUE TITLE
Error: arguments imply differing number of rows: 10, 9

### ISSUE THREAD

**Issue by MichelleDBG** [christianparobek/skeleSim#40]
I first installed the newest skeleSim, rmetasim, and strataG. I get the mentioned error.

![image](https://cloud.githubusercontent.com/assets/10090563/14256619/15b8ddca-fa57-11e5-81d4-8d5e753bdb22.png)

**Comment by stranda** [comment]
Thanks,
That's a known bug right now. I was waiting to fix until I had a better sense of how to convert the answers to the questions on the left panel into a recommendation
