### ISSUE TITLE
Error: connect reset by peer

### ISSUE THREAD

**Issue by MichelleDBG** [christianparobek/skeleSim#41]
Shiny crashed on me after I tried to reload Sean's connect_or_not example. Either I picked the wrong file to load (I did the R workspace with the title I gave it, not the .script.Rout, .script or .params created from trying runs). Any ideas on what's causing the error? 

Listening on http://127.0.0.1:5458
[1] "in matrixIn"
[1] "in matrixIn"
[1] "in matrixIn"
[1] "in mig.mat"
[1] "about to return from mig.mat"
[1] "in mig.mat"
[1] "about to return from mig.mat"
[1] "in mig.mat"
[1] "about to return from mig.mat"
[1] "in mig.mat"
[1] "about to return from mig.mat"
[1] "in mig.mat"
[1] "about to return from mig.mat"
[1] "in mig.mat"
[1] "about to return from mig.mat"
[1] "numloci 1"
[1] "numloci 1"
[1] "running anums()"
Warning: Error in observeEventHandler: no slot of name "num.sim.reps" for this object of class "skeleSim.params"
Stack trace (innermost first):
    64: observeEventHandler [make-skelesim-class.R#218]
     2: runApp
     1: skeleSimGUI
Warning: Error in FUN: no slot of name "num.sim.reps" for this object of class "skeleSim.params"
Stack trace (innermost first):
    81: FUN
    80: lapply
    79: sapply
    78: str.default
    77: str
    76: eval
    75: eval
    74: withVisible
    73: evalVis
    72: capture.output
    71: data.frame
    70: renderTable [debug.R#6]
    69: func
    68: output$ssClass
     2: runApp
     1: skeleSimGUI
ERROR: [on_request_read] connection reset by peer

**Comment by stranda** [comment]
my guess is that sean's object might have been created in a older version.  num.sim.reps is a new name for a slot that just was updated last week.
