### ISSUE TITLE
Crash with "Save example inputs for each scenario"

### ISSUE THREAD

**Issue by christianparobek** [christianparobek/skeleSim#43]
Just pulled installed the most up-to-date version (`install_github`) and running it with `skeleSimGUI()`. On the first page, when I click on the "Save example inputs for each scenario" button, it seems to crash: 

```
Warning: Error in [: subscript out of bounds
Stack trace (innermost first):
    68: cat
    67: write
    66: strataG:::.fscWrite
    65: fsc.write
    64: observeEventHandler [saveParams.R#38]
     2: runApp
     1: skeleSimGUI
```

**Comment by stranda** [comment]
I believe this one is fixed and now on github
