### ISSUE TITLE
How should we deal with single population simulations

### ISSUE THREAD

**Issue by stranda** [christianparobek/skeleSim#47]
If we simulate a single population, the simulation-analysis cycle crashes at the analysis stage.  

That actually makes sense because many of the summary stats are among (or across) population metrics.

Do we want to disallow single population simulations?  Or are there statistics that we want to keep in single populations (e.g. diversity stats)?

**Comment by christianparobek** [comment]
Ahh! Maybe that's what was the problem yesterday. Good find!

**Comment by stranda** [comment]
That's what I'm thinking, too.  I've now made a 2-population simulation default.  You can still run a single but for now, you can start skeleSim, push run simulation and get a reasonable result (though migration between the pops is pretty high) including analyses

**Comment by EricArcher** [comment]
I think it would be good to be able to do single population simulations (I'm working on a project with one now). I should be able to modify the analytical functions to handle this if the app can be modified as well (no migration matrix, etc.)

**Comment by stranda** [comment]
I think the app works correctly with single populations.
cheers,
a.

**Comment by EricArcher** [comment]
I just made an edit to analysis.funcs to only run pairwise analyses if @num.pops for the current scenario is > 1. While checking it, I had the output below on the console about the historical event check (I had not specified any historical events). If hist.ev is NULL, this error should not arise. Can you tell what its value is at this point? 

(Perhaps this should be a separate issue if it is not related to single population specification...)

  time source sink migrants new.size growth.rate migr.matrix
1 3213      1    0        1        1           0           0
  time source sink migrants new.size growth.rate migr.matrix
1 3213      1    0        1        1           0           0
NULL
NULL
'hist.ev' must have 7 columns.
[1] "hevck FALSE"
[1] "running growth.rates"
NULL
[1] "running growth.rates"
[1] "running samptime"

**Comment by stranda** [comment]
This this one is fixed.  The issue was that I was passing a 0 by 0 dimension matrix instead of NULL
