### ISSUE TITLE
"Help Choosing Simulator"

### ISSUE THREAD

**Issue by MichelleDBG** [christianparobek/skeleSim#49]
What are the magic set of answers that will result in selecting a forward-in-time simulation? To me it seems the "Coalescent simulator?" toggle button on the "General Conf" tab is the only way to switch between rmetasim and fastsimcoal. 

I'm sure I got it to switch before....

**Comment by stranda** [comment]
That's what issue #38 was getting at

**Comment by stranda** [comment]
I've got a version of the "help decide simulator tab" that has been pushed to github.  

This tab uses the basic logic that we outlined in the initial skeleSim discussions.  I have changed the weightings of the various questions somewhat to allow forward time simulations to be selected under certain circumstances.
