### ISSUE TITLE
Cannot find file

### ISSUE THREAD

**Issue by MichelleDBG** [christianparobek/skeleSim#50]
When I try to "Save skelesim parameter to file" from the Actions tab, I always get the error: 

Warning in normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\Users.... name.rdata": The system cannot find the file specified

**Comment by stranda** [comment]
Does it still let you save the file?

**Comment by MichelleDBG** [comment]
It does seem to let me save the file but only through the General Conf "Title" box. Then it only saves in the skeleSimShinyGUI folder, not in whatever root directory I set in the Actions tab.

**Comment by MichelleDBG** [comment]
I can find the file but it never has anything in the analysis.results slot

**Comment by stranda** [comment]
Did the skelesim object have an analysis.results slot populated before you save it?

Actually, this sounds like bad labeling on my part.  The save skelesim params file is intended to save the current state of the parameters.  It's what you might use if you were setting up a simulation and got called away from your desk and wanted to make sure you could pick up where you left off.  That could happen when you read the file you saved to disk.  The analysis.results slot only gets populated if you run a simulation.

As for the location of the file, the "save file" button ought to pull up a dialog box that lets you save anywhere.  Are you seeing a dialog box?

**Comment by stranda** [comment]
I've fixed the "file not found" warning message.
