### ISSUE TITLE
Cannot find fsc executable

### ISSUE THREAD

**Issue by christianparobek** [christianparobek/skeleSim#51]
Not sure if this is a bug or a system problem, but it's something I've all of a sudden started encountering. When I run any given sim it doesn't produce a results-containing Rdata file. So I worked through the `script.R` file and when I ran the `ssClass <- runSim(ssClass)` command I got back this:

```
sh: 1: fsc252: not found
Error in fastsimcoal(pop.info = fscPopInfo(pop.size = sc@pop.size, sample.size = sc@sample.size,  : 
  fastsimcoal exited with error 127
```

When I tab out `which fsc` on my system it returns `which fsc25221`, which makes me think I still have fsc installed, just that skeleSim is looking for `fsc252` instead. Oddly, in the GUI, under "Select fastsimcoal executable", `fsc25221` is the default. I've tried tracking this down using `ui.R` as a starting point, but no luck.

Thoughts?

**Comment by stranda** [comment]
can you look at the current ssClass tab in the GUI and see what fsc version
is actually listed in the fastsimcoal.exec slot?  Also, see if you can
change it with the pulldown.

On Thu, Apr 21, 2016 at 1:27 PM, Christian Parobek <notifications@github.com

> wrote:
> 
> Not sure if this is a bug or a system problem, but it's something I've all
> of a sudden started encountering. When I run any given sim it doesn't
> produce a results-containing Rdata file. So I worked through the script.R
> file and when I ran the ssClass <- runSim(ssClass) command I got back
> this:
> 
> sh: 1: fsc252: not found
> Error in fastsimcoal(pop.info = fscPopInfo(pop.size = sc@pop.size, sample.size = sc@sample.size,  :
>   fastsimcoal exited with error 127
> 
> When I tab out which fsc on my system it returns which fsc25221, which
> makes me think I still have fsc installed, just that skeleSim is looking
> for fsc252 instead. Oddly, in the GUI, under "Select fastsimcoal
> executable", fsc25221 is the default. I've tried tracking this down using
> ui.R as a starting point, but no luck.
> 
> Thoughts?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/christianparobek/skeleSim/issues/51

## 

Allan Strand,   Biology    http://linum.cofc.edu
College of Charleston      Ph. (843) 953-9189
Charleston, SC 29424     Fax (843) 953-9199

**Comment by christianparobek** [comment]
Ah, interesting find! Wow this is super weird. Even though it said fsc25221 in the dropdown menu, it said fsc252 in the ssClass. Then when I erased and retyped fsc25221 in the dropdown menu, it now populates as fsc25221 in the ssClass object.

Maybe this is just my computer being flaky. I suppose we can keep this in mind, but works for now!

Thanks!

**Comment by christianparobek** [comment]
I'm reopening this because this has still been giving me problems (though I haven't tried in last 24 hours) and because I just found a clue...

In the fsc.classes.R file, I found this: `fastsimcoal.exec = "fsc252"`.

Is there a reason that it says `fsc252` rather than `fsc25221`? If not, perhaps changing this would help solve the problem?

**Comment by stranda** [comment]
I'll take another look at this.

**Comment by thierrygosselin** [comment]
Not sure if it's normal behaviour.

Currently on macOS you need to have `fastsimcoal` binary, currently `fsc25221` in `/usr/local/bin` otherwise if it's just in the PATH (e.g. through `.bash_profile`) it just won't show in the `FastSimCoal Params` tab.

**Comment by EricArcher** [comment]
The installation vignette has been updated to indicate that the `fastsimcoal` binary needs to be in `/usr/local/bin`. I need to work on this with the `system` call in `strataG` to make it operate from folders in the PATH as desired.
