### ISSUE TITLE
Number of loci parameter specification

### ISSUE THREAD

**Issue by EricArcher** [christianparobek/skeleSim#53]
In following the Forecasting vignette, I've run into two issues trying to specify the number of loci in the Scenario Conf tab:

1) Changing the value in textbox did not change the vector size in Num. Alleles per locus in the Rmetasim Params tab. It was at 1 and when I changed it to 20, it did change the number of values in the Vector of mutation rates (Scenario Conf | Locus characteristics), but Num. Alleles per locus stayed with a single value.

2) After changing the number of loci to 20, then trying to change it back to 1 it gets into a non-ending loop where it seems to randomly cycle between 15 and 20.

**Comment by stranda** [comment]
Pretty sure the first issue is fixed.  
I've tested the second on several machines, but only linux and windows.  I can't seem to replicate, 
Both 1 and 2 are related, so could you try with the new version on github? thanks

**Comment by EricArcher** [comment]
Yes, this had been fixed. My problem was that I hadn't rebuilt skeleSim. Forehead slap.
