### ISSUE TITLE
growth.rate not a slot in fastsimcoal.params

### ISSUE THREAD

**Issue by christianparobek** [christianparobek/skeleSim#56]
On three different computers (2 Ubuntu, 1 Windows) I'm getting the following error:

```
> skeleSimGUI()

Listening on http://127.0.0.1:5513
Warning: Error in <Anonymous>: ‘growth.rate’ is not a slot in class “fastsimcoal.params”
Stack trace (innermost first):
    49: <Anonymous>
    48: fastsimcoalInit [/home/christian/R/x86_64-pc-linux-gnu-library/3.3/skeleSim/shiny/skeleSimShinyGUI/global.R#74]
    47: ssClassInit [/home/christian/R/x86_64-pc-linux-gnu-library/3.3/skeleSim/shiny/skeleSimShinyGUI/global.R#66]
    46: reactiveValues
    45: eval [serverInit.R#11]
    44: eval
    43: withVisible
    42: source
    41: server [/home/christian/R/x86_64-pc-linux-gnu-library/3.3/skeleSim/shiny/skeleSimShinyGUI/server.R#7]
     2: runApp
     1: skeleSimGUI
Error in (function (cl, name, valueClass)  : 
  ‘growth.rate’ is not a slot in class “fastsimcoal.params”
```

Going to try and track it down now, but posting it in case it rings bells with anyone else.

**Comment by christianparobek** [comment]
Error message tracks it down to `skeleSim/shiny/skeleSimShinyGUI/global.R#74`, which has:

```
fastsimcoalInit <- function(np){ #np num populations
    parms <- new("fastsimcoal.params")
    parms@growth.rate <- rep(0,np)
    parms@sample.times <- rep(0L,np) #must be integer
    parms
}
```

Seems to be the offending region. Perhaps this is an old code bit that needs to be removed or we need to go back and make the megalist object-maker function produce a `fastsimcoal.params` slot?

**Comment by EricArcher** [comment]
No, this needs to be read from a new object now. A while ago, I changed the way fastsimcoal parameters were specified, and both of these are in the pop.info matrix of the fastsimcoal class. Let me know if you want me to switch it or if you can work it out on your own.

**Comment by stranda** [comment]
I thought that we left these two slots in the fsc class after all.  Even though strataG uses the new pop object.  I create the pop object to be used in fastsimcoal() when the simulation gets run.   This greatly simplified the interface.  Did including these two slots cause the package to not pass checks?

**Comment by christianparobek** [comment]
Eric is it easy for you to switch it?

**Comment by EricArcher** [comment]
No problem. I'll put them back in now and document them in such a way that it passes the checks.

**Comment by EricArcher** [comment]
Done: growth.rate and sample.times moved back to scenario.params class and documented.

**Comment by christianparobek** [comment]
Great thanks! Reinstalled from github, but when run `skeleSimGUI()` I get the same stack trace as before. Perhaps I'm overlooking something?

**Comment by EricArcher** [comment]
Oh, I see the issue. Allan, you are assigning default values to @growth.rate and @sample.times as slots in a fastsimcoal.params object in global.R. Shouldn't these be slots in the scenario.params object?

**Comment by EricArcher** [comment]
Ignore the last - I'm adding both back to fastsimcoal.params. Sorry for the confusion - I'm jumping between three different projects now, and balls are getting dropped.

**Comment by EricArcher** [comment]
growth.rate and sample.times added back to fastsimcoal.params. Error should be gone now.
