### ISSUE TITLE
could not find function "graph.adjacency"

### ISSUE THREAD

**Issue by liblig** [christianparobek/skeleSim#57]
This is an error I received while attempting to specify the 'among population migration' in the 'Scenario Conf' of the GUI.

In my R console I also have the following: 
Warning: Error in renderPlot: could not find function "graph.adjacency"
Stack trace (innermost first):
    77: renderPlot [serverplots.R#9]
    69: output$networkPlot
     2: runApp
     1: skeleSimGUI

**Comment by stranda** [comment]
Please check that the "igraph" package is installed.  That should do the
trick.  I think that Eric is playing around with dependencies right now.
On Wed, May 25, 2016 at 7:01 PM, Libby Liggins notifications@github.com
wrote:

> This is an error I received while attempting to specify the 'among
> population migration' in the 'Scenario Conf' of the GUI.
> 
> In my R console I also have the following:
> Warning: Error in renderPlot: could not find function "graph.adjacency"
> Stack trace (innermost first):
> 77: renderPlot [serverplots.R#9]
> 69: output$networkPlot
> 2: runApp
> 1: skeleSimGUI
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/christianparobek/skeleSim/issues/57

## 

Allan Strand,   Biology    http://linum.cofc.edu
College of Charleston      Ph. (843) 953-9189
Charleston, SC 29424     Fax (843) 953-9199

**Comment by EricArcher** [comment]
I've added igraph back to Depends and removed from Suggests. This should solve it.

Hopefully, we'll be able to get an exemption for this Check NOTE when we submit to CRAN:

```
checking package dependencies ... NOTE
Depends: includes the non-default packages:
  ‘strataG’ ‘rmetasim’ ‘igraph’ ‘shiny’ ‘shinyFiles’ ‘markdown’
  ‘ggplot2’
Adding so many packages to the search path is excessive and importing
selectively is preferable.
```
