### ISSUE TITLE
Trying Rmetasim on Windows 

### ISSUE THREAD

**Issue by MichelleDBG** [christianparobek/skeleSim#65]
I get the following error and skeleSim crashes when I try to read skelesim object from file:

Warning: Error in [[: subscript out of bounds
Stack trace (innermost first):
    65: updateUIs [update-ui.R#99]
    64: observeEventHandler [loadParams.R#50]
     2: runApp
     1: skeleSimGUI
Warning: Error in [[: subscript out of bounds
Stack trace (innermost first):
    57: observeEventExpr
     2: runApp
     1: skeleSimGUI
Warning: Error in [[: subscript out of bounds
Stack trace (innermost first):
    57: observeEventExpr
     2: runApp
     1: skeleSimGUI
Warning: Error in [[: subscript out of bounds
Stack trace (innermost first):
    57: observeEventExpr
     2: runApp
     1: skeleSimGUI
Warning: Error in [[: subscript out of bounds
Stack trace (innermost first):
    69: reactive anums [rmetasim-server.R#66]
    58: anums
    57: observeEventExpr
     2: runApp
     1: skeleSimGUI
ERROR: [on_request_read] connection reset by peer

**Comment by stranda** [comment]
I reinstalled new versions of the various software and cannot replicate this issue on Windows 8

**Comment by MichelleDBG** [comment]
will try to upgrade R
https://github.com/hadley/devtools/issues/1137 

> install_github("stranda/rmetasim")
> Downloading GitHub repo stranda/rmetasim@master
> from URL https://api.github.com/repos/stranda/rmetasim/zipball/master
> Error: Could not find build tools necessary to build rmetasim

What are the 'build tools' that are necessary that I might not have? 

when I try 
install_github("stranda/rmetasim@master")

it seems to work.

**Comment by stranda** [comment]
Those are going to be "RTools" which can be found on the R website.  I used the Rmetasim from CRAN, however.

**Comment by MichelleDBG** [comment]
I downloaded RTools again, as administrator this time, but that didn't solve the problem. It only worked once I added "@master". Now I can run an rmetasim simulation and read the file and everything works fine.
