### ISSUE TITLE
Can't find fsc in PATH (I think)

### ISSUE THREAD

**Issue by MichelleDBG** [christianparobek/skeleSim#67]
Hello! I'm trying to use skeleSim from a new computer so I have to install fsc. I've got the path looking at the folder that holds the .exe 
In the FastSimCoal params tab, shouldn't the 'Select fastsimcoal executable' show the option "fsc25" in the drop down? It shows nothing. I tried typing it in, just "fsc25" but it didn't take the whole string (still some looping issues). I can't seem to run fsc and I can't tell if it a problem with the computer or path or skeleSim. 

Help?

**Comment by stranda** [comment]
can you give me the exact name of the executable?  fsc25.exe for example?

**Comment by MichelleDBG** [comment]
It is "fsc25.exe" in a folder that was called fsc25_win64 (or something). Tried changing the folder to "fsc25" and changing the path to reflect that. Changed the .exe to "fsc25.exe" after I downloaded it.

**Comment by stranda** [comment]
I think that you are going to have to try one of two things.

1) drop the file fsc25.exe into a folder that is in your PATH environment variable (c:\Program Files....) or
2) change the PATH environment variable to include the entire path to the folder in which you unpacked fastsimcoal.

cheers,
a.

**Comment by christianparobek** [comment]
Thanks Allan. Michelle were you able to get it working?

**Comment by MichelleDBG** [comment]
Yes! I made a new path to fcs but didn't make a new path in the system path. 

Now everything is working.
