### ISSUE TITLE
Coding suggestions

### ISSUE THREAD

**Issue by smhoban** [christianparobek/skeleSim#7]
I'm going to start a list of suggestions for code changes.

**Comment by smhoban** [comment]
In skeleSim.classes.R, the slot simulator, maybe we should change this from "c" and "f" to "fsc" and "rms" to match the two simulators we are using?  This would make the program more open ended in the future and seems like a good change for now?

**Comment by smhoban** [comment]
In skeleSim.funcs.R there is the runSim function... will this apply equally well to running rmetasim?  It looks like its calling the run function (which is in its own slot) and doing some tidying up, is that right?

**Comment by smhoban** [comment]
I couldn't find where fsc.locusParamsMat gets called- could you comment about where and what its used for?

**Comment by EricArcher** [comment]
I think it might be easier if each was its own Issue rather than one big Issue for all of the code. I'll split them out...
